apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "barely.fullname" . }}-api
  labels:
    {{- include "barely.api.selectorLabels" . | nindent 4 }}
  {{- with .Values.api.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "barely.fullname" . }}-ui
  labels:
    {{- include "barely.ui.selectorLabels" . | nindent 4 }}
