apiVersion: v1
kind: Service
metadata:
  name: {{ include "barely.fullname" . }}-api
  labels:
    {{- include "barely.api.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.api.service.port | default 8000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "barely.api.selectorLabels" . | nindent 4 }}
